export const SUPPORTED_LANGUAGES = {
    es: 'Spanish',
    en: 'English',
    fr: 'French',
    de: 'German',
    it: 'Italian',
    pt: 'Portuguese',
    ru: 'Russian',
    ja: 'Japanese',
    zh: 'Chinese',
    ar: 'Arabic',
    hi: 'Hindi',
    tr: 'Turkish',
    pl: 'Polish',
    nl: 'Dutch',
    el: 'Greek',
    ko: 'Korean',
    sv: 'Swedish',
    da: 'Danish',
    fi: 'Finnish',
    cs: 'Czech',
    hu: 'Hungarian',
    ro: 'Romanian',
    no: 'Norwegian',
    he: 'Hebrew',
    id: 'Indonesian',
    ms: 'Malay',
} as const

export const AUTO_LANGUAGE = 'auto' as const